### ISSUE TITLE
Letterboxd List Progress

### ISSUE THREAD

**Issue by nigelwarning** [frozenpandaman/letterboxd-userscripts#1]
Yoo!

I like this script. Now I can use it on Safari finally.
Is it also possible to port:
https://chrome.google.com/webstore/detail/letterboxd-lists-progress/cjpnlmdbmlefonmfkobjpfpmpbaijldn

Thanks!

**Comment by frozenpandaman** [comment]
@nigelwarning I'm glad! I'm pretty busy this time of year, sorry, but can try to look into porting that one too when I get the chance.

**Comment by frozenpandaman** [comment]
@nigelwarning Done! https://github.com/frozenpandaman/letterboxd-userscripts/blob/master/letterboxd-lists-progress.user.js

Merry Christmas!
